# Simple properties for 8GB RAM
org.gradle.jvmargs=-Xmx2G
android.useAndroidX=true
android.enableJetifier=true
android.ndk.suppressMinSdkVersionError=21
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.warning.mode=none

# Java home
org.gradle.java.home=C:\\AndroidStudio\\jbr

# Skip NDK version checks (helps with Agora)
android.experimental.disableNdkVersionCheck=true

# Auto-generate namespace for plugins (FIXES agora_uikit)
android.defaults.buildfeatures.buildconfig=true
android.namespaceAutoGeneration=true